### ISSUE TITLE
simice: bmpr -> bpmr (readme typo)

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#10]
bmpr A B [r|w|rw] = memory range breakpoint between locations A and B

should be

bpmr A B [r|w|rw] = memory range breakpoint between locations A and B

**Comment by simonowen** [comment]
Fixed in 3a2ecdd2ae0d7d55f7682bd777c47afbcd866e96 -- thanks!

**Comment by BalorPrice** [comment]
bpmr A B [r|w|rw] = memory range breakpoint between locations A and B

should be 

bpmr A B [r|w|rw] = memory range breakpoint at location A for B bytes

**Comment by simonowen** [comment]
Thanks also Howard! I only spotted that recently myself, while testing all the debugger commands again. It's not in the master branch yet though as my dev branch is still a bit volatile.
