### ISSUE TITLE
Should external RAM suppress ROM1?

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#11]
I'm running into crashes when loading sectors directly from B-DOS using dos hook code HMSRAD and setting page C to &80 for external RAM (megabyte).

The problem is that since DOS is continuously enabling interrupts that at some point an interrupt does fire. The SAM Basic IM1 interrupt handler then pages in ROM0 & ROM1 and jumps into ROM1. Here is the snippet from [samrom](https://github.com/simonowen/samrom/blob/master/main.asm):
````
           PUSH AF           ;38H INTERRUPTS
           PUSH BC
           IN A,(STATPORT)   ;READ IN ABOUT 36Ts (56) 6 (9) USEC
           LD C,A
           IN A,(250)
           LD B,A            ;B=LMPR, C=STATUS
           PUSH HL
           LD A,PAGE1F+&40
           OUT (250),A       ;BOTH ROMS ON, PAGE ZERO IN SECTION B
           LD HL,(ANYIV)
           JP (HL)

ANYI:      LD (SPSTORE),SP   ;ARRIVE IN ABOUT 113 (139) T 19 (23)
           LD SP,INTSTK
           CALL INTS ; <---- is in ROM1 - ie a jump into limbo if external can blank it out
           LD SP,HL
           OUT (250),A
           POP HL
           POP BC
           POP AF
           EI
           RET
````
However, when HMPR is set to external RAM, ROM1 is suppressed resulting in a crash.

I am seeing this in SimCoupe, I am _not_ sure if this is how a real SAM works or just an accidental implementation, io.cpp contains:

    // External RAM, ROM1, or internal RAM in section D
    if (hmpr & HMPR_MCNTRL_MASK)
        PageIn(SECTION_D, EXTMEM+hepr);
    else if (lmpr & LMPR_ROM1)
        PageIn(SECTION_D, ROM1);
    else
        PageIn(SECTION_D, (HMPR_PAGE + 1) & HMPR_PAGE_MASK);

Can anyone confirm if this is correct?

**Comment by simonowen** [comment]
I'm pretty sure you're correct, but I'll have to dig out my real hardware to check it.  I suspect the first two `if` conditions (and statement blocks) need to be reversed.

There was a bug in the same area a few years back, where turning off ROM1 failed to restore external memory underneath it.  It's possible that fixing that introduced this new bug -- I'll check the commit history.  It's possible it has been broken since the beginning, which would be an impressive find :)

**Comment by stefandrissen** [comment]
Anton Javorček posted this on Facebook:

> External memory has a higher priority than ROM1. This is no bug of SimCoupe, but "feature" of Sam Coupe.
> You can copy ROM1 to page in external memory and switch this page to section D before using DOS.
> SimCoupe1.0 have a bug in change LMPR, when external memory is paged in section C and D, section D is switched to internal memory or ROM1 according to LMPR.

So a real hardware check is definitely needed!

**Comment by simonowen** [comment]
The bug I remember changing a few years ago must be the one Anton reported.  That was in f3f476fd4ecc95f5a3974b27124e931f1ca364ce, which is already included in the release on GitHub. It sounds like external RAM having priority might be a feature, which isn't entirely compatible with existing software that might be using external RAM.

I haven't been able to unpack and set up real hardware to check it yet, but it's definitely needed to confirm this.

**Comment by simonowen** [comment]
I can finally confirm this when I go into the loft to get the Christmas decorations, and find a working SAM.  I've got a test program ready:

```
POKE 16384,243,62,127,211,250,62,129,211,251,62,123,50,0,192,58,0,192,79,6,0,62,1,211,251,62,31,211,250,251,201:PRINT USR 16384
```

If it prints 33 then ROM1 is overriding EXTRAM.  Any other value (123, 255, or maybe 0) suggests EXTRAM is overriding ROM1.

**Comment by simonowen** [comment]
I've _finally_ confirmed the existing behaviour as correct. External RAM does indeed cover ROM1.

This also fits with what the Technical Manual says about MCNTRL in HMPR:

> If this bit is set when the CPU addresses high memory, then the external signal XMEM goes low and the Coupe looks on its expansion connector for memory sections C and D.
