### ISSUE TITLE
simice: enter address: support numeric keys

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#16]
When entering an address in simice (using a), the numeric keys (on the right of a full keyboard) are ignored.

Additionally, being able to enter a label would also be helpful.

**Comment by simonowen** [comment]
Numeric keys and symbols is fixed in 5c5b97a02c5a79100b64a10ad33e5bc7f31c543f, and ROM symbol look-ups is fixed in 4ce9f6be6d8dc6f8adae335ca1e15e9ed660f253.

pyz80 symbol table look-ups should always have worked.  Let me know if you see any other issues.
