### ISSUE TITLE
Does an interrupt occurring directly after HALT:EI return to the correct address?

### ISSUE THREAD

**Issue by BalorPrice** [simonowen/simcoupe#17]
Interrupts that occur directly after a HALT:EI trap seem to store the program counter address as one larger than expected.  This then results in mis-execution of code once the interrupt has been completed.  Simple example:

	ORG &8000
	IM 1
	DI
	HALT
	EI

	LD BC,0
@loop:
	DEC BC
	LD A,B
	OR C
	JR NZ,@-loop

In this example, if you go into the debugger and manually move onto the EI instruction, then the interrupt appears to be trapped successfully after the LD BC,0 instruction has been run.  However, when it returns, the DEC BC instruction has been skipped.

**Comment by simonowen** [comment]
Thanks Balor.  This should be fixed in 666e5376fe29cfa0205bb73b3a5e2da652420867.

Are you building from source or will you need a new release binary?

**Comment by BalorPrice** [comment]
That's a *very* impressive turnaround speed, thanks.  I'd personally love a new release binary as I'm not a current generation developer at all.

**Comment by simonowen** [comment]
I can confirm it's fixed by 666e537 -- thanks for the code sample!

I'll work on getting an updated build that includes it.

**Comment by simonowen** [comment]
I've uploaded a [new Win32 build](https://github.com/simonowen/simcoupe/releases/tag/20200117). Please let me know if you have any trouble with it.
