### ISSUE TITLE
Does not start with certain non-ascii characters in path

### ISSUE THREAD

**Issue by snail-coupe** [simonowen/simcoupe#19]
Unpacked the 20200117 build into .../SimCoupé/...

When starting get an error about not being able to find samcoupe.rom - but the é in the path has got corrupted.  I _think_ this is because the path is encoded as UTF-8 <C3A9> but is being interpreted as ISO8859-1 <C3><A9>?

<img width="249" alt="simcoupé" src="https://user-images.githubusercontent.com/53581981/77481472-a33bd080-6e1b-11ea-8830-722bc7420d6f.png">

**Comment by snail-coupe** [comment]
workaround

simcoupe -rom .\samcoupe.rom

**Comment by simonowen** [comment]
For some reason I was asking for a utf-8 string, which wasn't going to work when passed to the regular APIs. I'll push an update shortly and update the release.  Thanks for the report!

**Comment by simonowen** [comment]
This is fixed in f277fa9c5ad8136403725e5fbc7a57bf89b601da. Please try the [new release](https://github.com/simonowen/simcoupe/releases).

**Comment by snail-coupe** [comment]
Looks good now. :-)
