### ISSUE TITLE
release build incorrect

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#22]
Not sure what happened, but the latest [pre-release](https://github.com/simonowen/simcoupe/releases/tag/20200524) with extended screen capabilities has incorrect assets. The assets are from the 2020**03**24 release.

**Comment by simonowen** [comment]
I build the binaries locally, and dragged in the wrong files because the older ones happened to be from a 24th. Fixed now, thanks!

**Comment by stefandrissen** [comment]
Just curious - why not deploy to release from Travis CI build?

**Comment by simonowen** [comment]
That's probably what I'll end up doing at some point -- it's on the ToDo list. It'd be good to have build artefacts automatically harvested from every master branch build.

The only difference between an automatic build and what I build is that the EXE is code signed, and I statically link the CRT and most other libraries, for wider system compatibility. It avoids the need for the appropriate vcredist to be installed, which is more of a problem on older OSes.

The code signing benefits are that SAMdiskHelper trusts SimCoupe.exe when it's signed, allowing raw access to Atom disk devices (ONLY) from non-elevated accounts. Code signing also avoids the untrusted software warning when launching the InnoSetup installer/uninstaller. The signing process can only be done locally, of course.

**Comment by stefandrissen** [comment]
Great!

I've not sorted out signing my installers in a pipeline yet either, you'd think something simple would be available for this.

I don't see setup.iss anywhere in this repository?

**Comment by simonowen** [comment]
I've seen a few projects encrypt the .pfx Authenticode certificate for use in AppVeyor scripts. though I'd be a bit wary of having my certificate and private key away from home! It might be better to have automatic unsigned releases and do periodic "official" manual signed releases, which have also had more testing.

The install.iss was pulled over from a development branch. It currently pulls files from a directory that only exists in my manual builds, so it's not ready to commit yet. I'll probably add a more generic version that uses the default `out` sub-directory used by Visual Studio.
