### ISSUE TITLE
options: only check relevant disk files

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#24]
Using 19th August 2020 release on Windows 10 x64.

The [ Tools / Options ] dialog checks files that are irrelevant for the current settings.

- drive 2
- select device type 'atom lite' 
- select fake file d:\atomlite
- ok

-> Invalid or incompatible disk: d:\atomlite

Which is fine.

Now change drive 2 device type to 'None'

-> Invalid or incompatible disk: d:\atomlite

Which is irrelevant.

**Comment by simonowen** [comment]
It keeps the different drive types active behind the scenes, and switches controller types when the options change. Though it does too much, re-inserting disks in case things have changed. I've never been very happy with that area of the code, and it's already on my list to improve -- hopefully soon.
