### ISSUE TITLE
Save Screenshot (PNG) broken

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#29]
If I use print screen or [ Record / Save Screenshot (PNG) ] the image is incorrect:

![simc0002](https://user-images.githubusercontent.com/5297464/98453589-29aee380-215b-11eb-9b82-e7ad6243df3b.png)

The above is with 'TV Aspect Ratio' enabled, if I disable this, then the horizontal duplication disappears, but vertically the image is still truncated:

![simc0009](https://user-images.githubusercontent.com/5297464/98453635-c3769080-215b-11eb-856b-ac93a914e85f.png)

**Comment by simonowen** [comment]
I've not been able to reproduce this with the latest 20200827 release or the development build.  Are you definitely using the latest code or release build?

I'm getting the same (and correct) image size with both option settings:
```
$ file simc0061.png
simc0061.png: PNG image data, 576 x 480, 8-bit colormap, non-interlaced
```

The image width is taken from the width of the internal framebuffer, which doesn't change with the aspect option.

I do remember some issues after early refactoring over the summer. I refactored all the PNG saving to use libpng in f6ef97f980391270789e663e2ef0835297157792 on 21st August 2020, which makes things a lot simpler than before.

**Comment by stefandrissen** [comment]
Thanks! I was using the 19th August build - after updating to the 27th it's fine.
