### ISSUE TITLE
Alt+Enter and View->Full Screen both immediately exits SimCoupe (latest Win build) instead of switching to fullscreen

### ISSUE THREAD

**Issue by stripwax** [simonowen/simcoupe#31]
On launch, I now see that the menu item for Full Screen on View menu is already selected (even though the application is NOT full screen i.e. it is windowed but "Full Screen" already seems selected.  In which case, I guess the crash is caused by 'turning off fullscreen' rather than turning it on, but that's confusing too)

**Comment by stripwax** [comment]
Actually this looks like a configuration issue.  I upgraded SimCoupe 1.0 in-place with the contents of SimCoupe-20200827.zip , leaving SimCoupe.cfg in place.  A fresh install into an empty folder has no such issue and fullscreens ok.

**Comment by stripwax** [comment]
Config attached (dated 28 02 2009)
[SimCoupe - Copy.cfg.txt](https://github.com/simonowen/simcoupe/files/5632843/SimCoupe.-.Copy.cfg.txt)

**Comment by stefandrissen** [comment]
I'm having similar issues - will check if it is also the cfg.

Also when switching to another application (when not in full screen mode) the SimCoupe window minimizes.

**Comment by stripwax** [comment]
So actually...  even though I reported the symptom as the application exiting, I later (much later!) noticed I had many multiple copies running, headless as it were, according to task manager. So most likely the fullscreen option was hiding the window rather than exiting..

**Comment by simonowen** [comment]
Thanks both, I can see the effect locally too. It does feel like a state mismatch causing it to apply the changes in the wrong version.  It should also restore fullscreen mode on the next startup if that's how it was when you quit, and that seems to be broken.

**Comment by simonowen** [comment]
Fixed in b058279667c73e18a2e321d52b3aa20540d3f6e5, which is part of the [20210501 build](https://github.com/simonowen/simcoupe/releases/tag/20210501).
