### ISSUE TITLE
tape browser: invalid tap triggers crash

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#34]
Intrigued by [a question](https://spectrumcomputing.co.uk/forums/viewtopic.php?f=23&t=2718&sid=28db7225f8921590d9ef51ce850cb723) on how to record to tape.

- create an empty file named tape.tap
- open the tape browser with F3 or menu
- select tape.tap

````
---------------------------
Microsoft Visual C++ Runtime Library
---------------------------
Runtime Error!

Program: C:\Program Files (x86)\SimCoupe\SimCoupe.exe

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
````

**Comment by simonowen** [comment]
Fixed in 2a07e7bf6aaa3343e5f088382357055291e148a5, which is currently in the dev branch. I've changed it to reject zero-sized images, which libspectrum accepted but later failed to handle correctly.
