### ISSUE TITLE
SpeedUpError

### ISSUE THREAD

**Issue by AntonyDTA** [simonowen/simcoupe#35]
If Interrupt is permanently disabled, pressing the Keypad "+" for increase emulation speed will cause error. Any speed selected via the menu: System/Speed/ is OK. Also Keypad "-" for decrease speed is OK.
Simply for show:
 DI
Loop:
 LD A,&10
 OUT (&F8),A
 LD A,&00
 OUT (&F8),A
 JR Loop

**Comment by simonowen** [comment]
Thanks for the code sample!  I've reproduced it but haven't investigated yet. I'll add details here when it's fixed.

**Comment by simonowen** [comment]
I've pushed a fix for this to the `dev` branch, and it'll be included in the next release package.

Thanks again for your detailed report and code sample.

**Comment by simonowen** [comment]
Fixed in f3fd0418e7e69ad8a39abb9cc4b79d599d09b6c2 is part of the [20210501 build](https://github.com/simonowen/simcoupe/releases/tag/20210501).
