### ISSUE TITLE
SSX Format

### ISSUE THREAD

**Issue by spectrumcomputing** [simonowen/simcoupe#37]
Hi Simon,

Thanks for implementing the SSX format.  Pavel from the forums noticed that we seem to be  having some issues with Mode 4 games.  For example:

https://www.worldofsam.org/products/captain-comic

The intro screen is the correct size, but the run screen comes out 4 times the size (in bytes) than it should be. I enclose the two screens.  I have renamed them as .txt so I could upload them.

[Running.ssx.txt](https://github.com/simonowen/simcoupe/files/5905806/Running.ssx.txt)
[Intro.ssx.txt](https://github.com/simonowen/simcoupe/files/5905807/Intro.ssx.txt)

Many thanks

**Comment by stefandrissen** [comment]
Hi Peter,

With what version of SimCoupe did you produce the running screen? If I capture both intro and running screen with the latest release of SimCoupe, they are both 25k.

There were some issues with a previous build, see for example #29

**Comment by spectrumcomputing** [comment]
Hi Simon,

Looks like we were using the version from May referenced here:

https://spectrumcomputing.co.uk/forums/viewtopic.php?p=37338#p37338

I can confirm the new version works fine.  

I will add a link to the later version on the forums. 

Best wishes

Peter

**Comment by spectrumcomputing** [comment]
OK, sorry to open this again, but we have done some more testing, as mentioned Captain Cosmic is fine, but The Bulgulators creates a 96K file. 

We are on SimCoupe-20200827

Details, are here onwards

https://spectrumcomputing.co.uk/forums/viewtopic.php?p=57406#p57406

Many thanks

**Comment by stefandrissen** [comment]
The Bulgulators is changing the palette on line interrupts (starting at line 64 and then every 16 lines after that), so SimCoupe switches to RAW format (which is 96K) to capture the entire image (see https://github.com/simonowen/ssxview).

The loading screen: https://spectrumcomputing.co.uk/SCRtoImage.php?SCR=zxdb/sinclair/entries/0034991/0034991-load-1.ssx&border=0
The in game screen: https://spectrumcomputing.co.uk/SCRtoImage.php?SCR=zxdb/sinclair/entries/0034991/0034991-run-1.ssx&border=0

If SCRtoImage.php is creating a double size screen with a **current** SSX, then I would guess that there is an issue with SCRtoImage.php

**Comment by simonowen** [comment]
@spectrumcomputing: sorry for the delay in responding.

I agree with @stefandrissen's analysis. Only simple static images will be saved using the smaller MODE formats. If the SAM program performs any video changes _during_ the scan-out portion of the main display the image must saved using RAW format to preserve the dynamic changes. This is true even for SAM boot-up screen, which changes colour of palette entry 0 for the coloured stripes, even though the final visible image appears to be static.

I'll close this issue, but please re-open it if you still think there's a problem with SimCoupe. I suspect SCRtoImage may not be handling the RAW format files correctly.
