### ISSUE TITLE
Animated gif - only saving half screen

### ISSUE THREAD

**Issue by davidimpress** [simonowen/simcoupe#38]
Latest packaged build is only outputting the upper half of the animated gif when saved

**Comment by simonowen** [comment]
Thanks for reporting this.  I've pushed a fix to the `dev` branch, which will be in the next release package.

**Comment by simonowen** [comment]
Fixed in 955bb1189200a61a5a166e9984eed60f8abf094d is part of the [20210501 build](https://github.com/simonowen/simcoupe/releases/tag/20210501).
