### ISSUE TITLE
Mute Sound

### ISSUE THREAD

**Issue by davidimpress** [simonowen/simcoupe#39]
Mute Sound option is missing from system menu on latest build

**Comment by simonowen** [comment]
I removed it as it seemed unnecessary for modern OSes, which have per-application volume controls. Over time it's generated a couple of No Sound support emails when people hadn't noticed they'd accidentally toggled it.

Do you have a specific use case that still requires it?

**Comment by davidimpress** [comment]
Can work around it - just checling it was an intentional removal.
Thanks
