### ISSUE TITLE
Sim Ice - editing value in numeric mode..

### ISSUE THREAD

**Issue by davidimpress** [simonowen/simcoupe#41]
Sim Ice - editing value in numeric mode - misalligns the values when displayed on screen.

![image](https://user-images.githubusercontent.com/49476403/108633652-3edf2200-746d-11eb-8b51-7b05586297ef.png)

Date inputs correctly - just appears alligned incorrectly until enter pressed.

**Comment by simonowen** [comment]
Good spot, thanks!  Fixed in the `dev` branch, so it'll be in the next release package.
