### ISSUE TITLE
SimICE: show samdos labels

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#44]
I am currently debugging some samdos calls, it would be nice if the samdos labels could be shown.

**Comment by simonowen** [comment]
It might be a bit late for LLLL but maybe future projects!

The same commit also fixes an issue where you could only use symbols in expressions the _first_ time you opened the debugger. For example, pressing A to change address and entering "nmi" to go to the ROM NMI handler. It affected all symbol-to-address reverse mappings from the second and later times the debugger was entered for any reason.
