### ISSUE TITLE
SimICE: view screen

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#46]
While debugging, the actual screen based on the display raster is shown. So if the raster has passed the screen area being updated, the updated screen is not yet shown - which is accurate and fine.

If however I want a preview of what the screen will look like when the raster beam passes again, I can use the graphics view and change the width to 128. 

A quicker key combination or separate view would be useful.

**Comment by simonowen** [comment]
After some thought on how it should work I've added this as a toggle to control what is seen when the debugger is active, so it doesn't affect the normal running mode. You can switch between the modes using a new menu item on the Tools menu.

The toggle action can be bound to a function key but doesn't currently work when the debugger is open. That limitation should disappear when the built-in GUI is changed/removed.
