### ISSUE TITLE
Border area changes aspect ratio

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#47]
Using window size 100% and TV Aspect Ratio.

Border area Medium (default):

![image](https://user-images.githubusercontent.com/5297464/117530036-46798600-afdb-11eb-921d-7a03b07f59f5.png)

Border area Large (TV-visible):

![image](https://user-images.githubusercontent.com/5297464/117530066-6ad56280-afdb-11eb-8bf1-cbc56e0cd74b.png)

When switching between these two border areas, the height of the image changes but the width does not, so the aspect ratio is getting lost.

**Comment by simonowen** [comment]
Good find!  If the aspect ratio of the source canvas changes the target will need to be updated too.  I could only see it in action by toggling the aspect ratio after making the border change.

I've pushed a small fix to correct it -- thanks!
