### ISSUE TITLE
Shell 'Boot with SimCoupe' / 'Open with SimCoupe' do not work as expected

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#49]
While trying to get some handle on #48 - I had a closer look at how I was starting SimCoupe.

The installer adds two context menu entries with a slightly different registry command:

- **Boot with SimCoupe** - ...\SimCoupe.exe" "%1"
- Open with SimCoupe - ...\SimCoupe.exe" "%1" -autoboot 0

However, how both context menu entries work is identical:

- if Helpers option 'Auto-load media inserted at startup screen' is ticked, both will boot;
- if the Helpers option is not ticked, both will not boot.

**Comment by simonowen** [comment]
The option was completely broken and just ignored, but should be fixed by the commit above.  Thanks for the report!
