### ISSUE TITLE
Keyboard input does not work properly on Fedora 28

### ISSUE THREAD

**Issue by EtchedPixels** [simonowen/simcoupe#5]
If you type a few digits then delete them you get one deletion only, other keys begin to stick a bit as if key-up events are not always being processed properly.

Switching input mapping doesn't seem to help

**Comment by EtchedPixels** [comment]
Seems to be because I built it without SDL 2, soon as I opened the bug I realized.. duh

**Comment by simonowen** [comment]
The input code should still work with SDL 1.x, so if it didn't for you there may be an issue to investigate.

SDL 2 is still preferred overall as the video support is accelerated.
