### ISSUE TITLE
Disk image corruption.

### ISSUE THREAD

**Issue by AntonyDTA** [simonowen/simcoupe#57]
Save to disk image (.dsk) will corrupt the disk image!
Will cut first 256 bytes from file.

**Comment by simonowen** [comment]
EEK!  I've removed the v1.2.1 release and will release a fixed v1.2.2 later today. Thanks for letting me know!

I think this bug affects EDSK saving, with MGT and SAD working correctly.

**Comment by simonowen** [comment]
This should be resolved in the [v1.2.2 release](https://github.com/simonowen/simcoupe/releases/tag/v1.2.2).
