### ISSUE TITLE
Record video as GIF

### ISSUE THREAD

**Issue by AntonyDTA** [simonowen/simcoupe#59]
"Record/Video as GIF" saves low resolution only.

Can be modified as AVI:
Record Animation
Record Animation Half Size
Record Loop
Record Loop Half Size

Or name it as:
Video as GIF (LoRes)

**Comment by simonowen** [comment]
At the time GIF support was added I think Internet Explorer was still one of the most used browsers and it didn't handle the full size or 50fps animations well. That's no longer true for modern browsers so I can probably (optionally) record in full size now.  I'll look into it...

I was considering replacing the AVI support with modern video encoding using a 3rd party library. The existing AVI support is lossless but uses an old codec (MS-RLE) that isn't supported by all players. It might be good to encode directly to the user's choice of video codec instead.

**Comment by AntonyDTA** [comment]
AVI compression doesn't need to be changed, RLE is the basis and I certainly wouldn't change it for some lossy compression.

**Comment by simonowen** [comment]
I've added this to the [v1.2.3 dev release](https://github.com/simonowen/simcoupe/releases/tag/v1.2.3), plus support for higher GIF framerates (50fps is the new default).
