### ISSUE TITLE
Can no longer open zipped dsk images

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#61]
When opening a zipped disk image or dragging a zipped disk image to SimCoupe 1.2.2 it is no longer opening but just showing an empty disk.

![image](https://user-images.githubusercontent.com/5297464/129276897-efc20de1-dbbd-4556-8802-a0935c4f91e1.png)

With 1.1 Alpha this was working.

[FRED Issue 76 (1997)(-).zip](https://github.com/simonowen/simcoupe/files/6978823/FRED.Issue.76.1997.-.zip)

**Comment by simonowen** [comment]
Fixed in the [v1.2.3 dev release](https://github.com/simonowen/simcoupe/releases/tag/v1.2.3).
