### ISSUE TITLE
 length of label names in Trace

### ISSUE THREAD

**Issue by AntonyDTA** [simonowen/simcoupe#63]
The length of label names in SimICE / Trace is 12 characters, but free space is for 15 characters. You can change it to at least 14 characters as in my Comet assembler.
And can you add creating .map file of labels from running Comet in sam memory?

**Comment by simonowen** [comment]
I can see where it's limiting the label length to 12, even though the field size is 16. It can now use the full field size.

I've also enabled labels in the disassembly section when symbols are enabled for the address field. Previously it would only disable addresses to save space. There isn't enough space to show longer labels, but you should see up to about 12 characters. It's still a bit cramped under some conditions, but I'd rather improve that in a new debugger interface.

![trace_symbols](https://user-images.githubusercontent.com/200089/130358313-55513687-d101-46ad-aea7-27712307c67f.gif)

**Comment by simonowen** [comment]
It should be possible to support Comet symbols, but there may be less context available on which to use. The symbols from pyz80 are only address symbols, with EQU symbols ignored as they could be lengths or other non-address values. Scraping from memory may mean ALL symbols, which could generate some unwanted matching.

I'm hoping that recent improvements to symbol context will avoid them, but if not I may have to filter values under 256 or something. I'll try it and see what happens...

**Comment by AntonyDTA** [comment]
Yes, values below 256 can be confusing, but also addresses with more labels in other pages or also in the same page.
This can be edited manually, for example in Notepad.
Your debugger had no problem with that, it only displayed the first (or last) label name, I don't remember anymore.

[CometSrc2DebugMap.zip](https://github.com/simonowen/simcoupe/files/7027807/CometSrc2DebugMap.zip)
I added my basic program to create .map file from Comet v1.8 .

**Comment by simonowen** [comment]
Please try the new [v1.2.4 release](https://github.com/simonowen/simcoupe/releases/tag/v1.2.4) and see if it works as you expect.

**Comment by AntonyDTA** [comment]
Yes, according to my quick test it works very well, but ...
My idea was to create a real file in the disk image folder, for possibility of editing.
You can only add an option in the menu, something as: "Create .map file in the disk image folder" or only "Create .map file".
This .map file must always be loaded when entering the debugger, for its parallel editing.
Creating .map file must be controlled by user and incorect .map file is its stupidity.

**Comment by simonowen** [comment]
I think that should just be a simple addition to what I've done already. Currently it looks for a .map file matching the disk image file in drive 1, and if that's not found it'll look for Comet symbols. That seems to be good default behaviour for most users.

I can add a feature to save the current user symbols to a file, either prompting for a file or using the name of the disk in drive 1. Once the file exists it will be used instead of the live Comet symbols. Changes are reloaded when entering the debugger, so any edits will be seen immediately.

If you assemble new code in Comet it will still use the old file, so you'll need to export fresh symbols to see the changes.

**Comment by AntonyDTA** [comment]
That's exactly how I imagine it.
The file name and path have already been defined.
Automatic file creation conflicts with the possibility of editing.
This function can be as a command in the debugger, or as an item in the "Tools" list, under "Raster Debugging".

**Comment by simonowen** [comment]
Improved in [v1.2.6](https://github.com/simonowen/simcoupe/releases/tag/v1.2.6).
