### ISSUE TITLE
CP/M disk handling broken?

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#64]
Reported by Edwin Blink on sam-users mailing list:

> I was playing a bit with  prodos v2 and noticed I get a read only error with current simcoupe buid  (1.2.5) 
> 
> Example:
> 
> - Boot [Prodos v2](https://www.worldofsam.org/products/pro-dos) disk in simcoupe
> - from menu:  new DOS CP/M disk
> - format  b: -> OK
> - copy a: b:  -> is read only error
> - format b: -> Format error 
> 
> Didn’t have any issues when using simcoupe 1.0

**Comment by simonowen** [comment]
Fixed in [v1.2.6](https://github.com/simonowen/simcoupe/releases/tag/v1.2.6).

**Comment by dddfffggg777** [comment]
format b: -> ok
b:
dir -> list of "???????" names
