### ISSUE TITLE
SimICE: bpio only traps first breakpoint

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#70]
The following plastic example illustrates the issue, set two port breakpoints. The first condition is always false, the second is unconditional:
``bpio f8 if 1==2``
``bpio f8``
Reset SimCoupe, the second breakpoint is never triggered.
Now disable the first breakpoint and reset SimCoupe.
The second breakpoint is triggered.

While trying to get the right syntax / condition for a port breakpoint I was just creating a subsequent breakpoint with a new attempt, now I know that I must disable or delete the previous port breakpoint attempt.

A simple documentation note would be fine resolution, I was not trying to enable multiple breakpoints, I was just experimenting.

**Comment by simonowen** [comment]
Fixed in [v1.2.8](https://github.com/simonowen/simcoupe/releases/tag/v1.2.8) or later so the second breakpoint will trigger as expected.
