### ISSUE TITLE
SimICE: allow pasting to command line

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#71]
As a quick fix, could the debugger command line accept pasting of clipboard contents?

I'm a pretty quick typist, but repeatedly having to type:

``bpio ff if peek(pc+2)==51 and dline>=0n258``

Is starting to drive me nuts.

**Comment by simonowen** [comment]
This is now supported in [v1.2.8](https://github.com/simonowen/simcoupe/releases/tag/v1.2.8) or later, along with the command history (cursor up/down in the debugger command-line control).
