### ISSUE TITLE
Feature Request: Support for keyboards without numpads

### ISSUE THREAD

**Issue by snail-coupe** [simonowen/simcoupe#73]
My laptop doesn't have a numpad, not even a modifier key to remap some of the regular keys as a NumPad. Which means I don't have a way of generating e.g. the Sam's F9 key.

Is there anything that could be done to make these keys available? (Ctrl-Shift-Fn = Fn?)

I don't remember if the Sam supported doing things like Shift-F9 so that may not actually work :-(

**Comment by snail-coupe** [comment]
I've just been reading the source code and discovered you can already do Win+Fn = Fn.

**Comment by simonowen** [comment]
The only issue with using regular modifiers keys is that they can no longer be used with the SAM keys they're accessing. The current approach of using the Windows key is risky as Windows uses it, currently only for Win-F1 to open a help page. I've made a change to add Win-F11 as alternative way to access SAM F1, and also added the missing documentation.

I'm not sure if there's a good alternative key that's widely available on laptop keyboards. Alt-Gr is used for the natural SAM Cntrl key, but _could_ be optionally repurposed. The backtick is used for (c) and the Apps key for Edit. SAM just has too many special keys!

**Comment by snail-coupe** [comment]
Thanks.

I was surprised my laptop doesn't have a modifier to generate them. Maybe this is the excuse I need to get a MacBook Pro 😂
