### ISSUE TITLE
Saving BASIC routine

### ISSUE THREAD

**Issue by Retrogamebloke** [simonowen/simcoupe#78]
Just been playing with this emulator and cannot see any way to save a basic program. Is it possible to save code as a tape or disk file? A snapshot type system would be useful as well, but a way to save as proper tape/disk files would be preferable :)
Would make it far better for playing with SAM BASIC programming.

**Comment by simonowen** [comment]
The most natural way to do that is using disk images:

1. Use File->New in SimCoupe to create and insert a new .MGT disk image , or open an existing disk image.
2. Type `BOOT 1` to load DOS for the disk access commands (after every hardware reset).
3. then `SAVE "YourProg"` and `LOAD "YourProg"` etc. as normal. `DIR 1` for directory listing.

For smaller programs I sometimes use Tools->Paste to paste a BASIC listing from the clipboard into SimCoupe. It's also possible to add a printer to Parallel Port 1 in the options, then use `LLIST` to export the BASIC listing to a .txt file.

If you're new to the SAM you might find some of the [reference manuals](http://www.samcoupe-pro-dos.co.uk/sammanual.html) useful. The SAM BASIC manual for general BASIC programming and the SAM Drive manual for more details about DOS use.

Tape loading is supported but not tape saving yet. Snapshot support is coming but there's a bunch of code refactoring needed before it'll be available in public builds.

**Comment by Retrogamebloke** [comment]
Thanks a lot for the info. Totally new to the SAM, always wanted one back in the day. Great work on the emulator! I hope to have some fun comparing how fast the basic was compared to the Speccy! I remember one mag saying it was 70% as fast as an Atari ST at the time :) Be interesting to see how some actual games run as well, but not tried any yet.

**Comment by stripwax** [comment]
Yep, you can create a "virtual" disk (a .dsk file) using the menu, and
save/load using that.
