### ISSUE TITLE
simice font rendered incorrectly when window size 200% or 300% and viewing complete border area

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#8]
I am unsure what is triggering this, but certain combinations of window size and border area are resulting in a poorly rendered simice font. The following is at 200% + complete border:

![image](https://user-images.githubusercontent.com/5297464/47928484-cc765c80-dec6-11e8-9cb4-34cb8c167738.png)

If I lower the border size to medium, it's fine:

![image](https://user-images.githubusercontent.com/5297464/47928657-21b26e00-dec7-11e8-8265-34513c360769.png)

If I use 150% and complete border it's also fine:

![image](https://user-images.githubusercontent.com/5297464/47928710-3d1d7900-dec7-11e8-9835-7b06561dd85e.png)

**Comment by simonowen** [comment]
I recognise the issue, and I thought I managed to hide it in most cases!  There must be an issue with the way it matches the window size up with scaling values, which I'll try to reproduce.

The built-in GUI is drawn using the same canvas as the emulated SAM display.  At the time it seemed like a good idea as it gave a "free" GUI on all platforms, without needing to implement a new native version for each. The drawback is that it's limited to the same resolution as SAM's mode 3, albeit with double the vertical resolution too.  On modern systems the window is scaled up quite a lot, and the low source resolution really starts to show.

SimCoupe tries to make the best of this by selectively filtering the output image. When it thinks the scaling is a simple multiple it uses point filtering for a sharp image. In other cases it uses a filtered image, which can be a bit blurry, especially when scaled up a lot.  It tries to convert the current window size back to a simple scaling factor, to decide which case to use. When you resize the window by the edges it should snap to half-multiple scaling points, which should alternate between sharp and blurry.   Something about the change of border area must be throwing out that calculation, causing it to use point filtering when it's not a multiple, which gives the ugly text you're getting.

A short-term work-around might be to force the GUI to always use filtering, which ensures you never get the ugly text. Though it also means you won't ever get the sharp text either.  You can force it with a hidden option in %APPDATA%\SimCoupe\SimCoupe.cfg  Change the existing FilterGUI to Yes.

The whole built-in GUI needs completely refactoring to use modern text rendering at native display resolution.  Under Windows you only see it used in the debugger, but on other platforms the options, file selectors, and other dialog boxes all use the same system, with custom widgets implemented in the same way.  Replacing it will be a fair amount of work, but really does need to be done sometime. When it's only one person working on it, and only one project of many fighting for time and inclination, these things can take some time do get done :)

I've a bit reluctant to go the QT route, but something along those lines might give the widgets, text, and graphics that could replace the built-in version.  I'll have to give it some thought when I'm properly back on the project.

**Comment by stefandrissen** [comment]
FilterGUI=yes does the trick as far as I'm concerned.

Ultimately I agree that moving the debugger out of the SAM's display to a separate window is the way to go, now it just gets in the way.

One thought I had about addressing the user interface concerns on various platforms, was to expose (and control) the internals from a web browser. :-)

**Comment by simonowen** [comment]
I'm still experimenting with options for this.  Going QT for GUI would work for major platforms, but be less flexible on frame-buffer only setups.  I'm looking at options for better native rendering text and widget that could be either inline or a separate window.

**Comment by simonowen** [comment]
While I'm still working towards replacing the built-in GUI, other changes I've been making should improve this issue in the meantime.  The problem with the current version is that it is all or nothing between point sampling and bilinear filtering. Point sampling gives ugly scaling on non-multiples, and filtering typically makes everything too soft.

I've left a smoothing option that gives the same as the current filtering for the emulation, with smoothing now forced off in the GUI. To fix the ugliness I point sample an integer scaled version of the original to maintain sharpness, then filter any difference in scaling to the required target size. This gives sharp text at 100% multiples, and a little filtering elsewhere.

Here's 150% scaling, which was previously quite soft with filtering:

![sc_150](https://user-images.githubusercontent.com/200089/73127393-7738d600-3fb7-11ea-9d50-e26d22ba3bfe.png)

Stretching that up a little more for around 160%-ish:

![sc_160ish](https://user-images.githubusercontent.com/200089/73127402-8d469680-3fb7-11ea-9559-5a5e6dd05de0.png)

I've still not finished hacking the display side, but hope to have a branch with the changes before too much longer.

**Comment by stefandrissen** [comment]
Looking very nice!

**Comment by simonowen** [comment]
This is fixed by a4c8b00b4cf42028ac3087d666c3b796cac64135, which is part of the [20200819 build](https://github.com/simonowen/simcoupe/releases/tag/20200819).

When smoothing is disabled (or the GUI is active) the display uses integer scaling up to the nearest multiple, then bilinear filtering for any remaining difference. This will fix the ugly scaling artefacts seen in your original image.
