### ISSUE TITLE
Launching games via command line not working on macOS

### ISSUE THREAD

**Issue by leonstyhre** [simonowen/simcoupe#82]
I've been adding support for SimCoupé to my emulator frontend ES-DE (https://es-de.org) and it works perfectly fine on Linux and Windows. However for the macOS release I'm unable to launch any games from the command line.

Could you please look into this so I can add support for SimCoupé also for this operating system?

And another thing, there are some dead download links on the SimCoupé website so it would be great if you could fix that as well!

Thanks in advance!

**Comment by simonowen** [comment]
It was inserting the disk image but the auto-boot request was getting lost. Normal command-line processing handled it correctly but Finder was also passing the disk as an opened file, which trampled on the earlier processing.

I've pushed a fix for this to main, which also fixes launching disk images from file associations.  It'll be in the next official release, but you can grab the [CI build](https://github.com/simonowen/simcoupe/suites/7347832492/artifacts/297897878) if you want to try it sooner.

I've also updated the website links to version 1.2.11. There was a hotfix version of 1.2.10 for macOS and the link wasn't updated to point to the newer point release, so I think it was only that one not working.

Thanks for reporting!

**Comment by leonstyhre** [comment]
Thanks for fixing this so quickly! I've tested it and can confirm that it resolves the issue on macOS.
