### ISSUE TITLE
Version number incorrect?

### ISSUE THREAD

**Issue by bodhi-baum** [simonowen/simcoupe#87]
Well, this is a minor issue I guess, but is it possible that the version number in the latest releases is not correct? 

When I install version 1.2.11 under Linux, 1.2.8 is displayed. That confuses a bit.

**Comment by simonowen** [comment]
That's odd as the version number should only exist in one place in the source code in recent-ish versions. Updating that should automatically update the versions used everywhere in the program.

Are you using the 1.2.11 version from the Releases section on GitHub?  If not, do you have a link to the one you installed?

Also, are you looking at the version shown in the About box in the Options?  Looking at the built-in GUI version of the About box using the Windows version of 1.2.11 does show the correct version, so the Linux version _should_ be correct too:

![image](https://user-images.githubusercontent.com/200089/207935000-01e1c8ba-5aa3-46ed-96f9-fe0f55a8d1bd.png)

I'll have a check of the Linux build in a VM when I get the time.

**Comment by bodhi-baum** [comment]
I installed the latest .deb. When looking at the about message it tells me 1.2.8. However, my installation programme says version 1.2.11 is installed.

**Comment by bodhi-baum** [comment]
Yes, you are right. The culprit was hidden there. After deleting the file, I now get the correct version displayed when I start.
