### ISSUE TITLE
SimICE:

### ISSUE THREAD

**Issue by AntonyDTA** [simonowen/simcoupe#88]
Memory pointer address displayed incorrectly.
Instead of memory around address 8300 (8302-02) it shows memory around address 8400. But the instruction executes correctly.
![SimICE_Bug](https://user-images.githubusercontent.com/68946405/210627838-03312d38-eab8-4a49-9824-802eb6e6167f.png)

**Comment by simonowen** [comment]
It looks like it's adding 0xfe to IX as an offset instead of the (signed) -2 value. It's only a view issue where it's calculating the target address from the instruction to assist in debugging.

I'll get that fixed soon -- thanks for the report!

**Comment by simonowen** [comment]
Fixed in [v1.2.12](https://github.com/simonowen/simcoupe/releases/tag/v1.2.12) release.
