### ISSUE TITLE
record to wav is skipping silence

### ISSUE THREAD

**Issue by stefandrissen** [simonowen/simcoupe#9]
SimCoupe 1.1 alpha
Windows 10 x64.

I wanted to create an oscilloscope video of Electro-1 (https://zxart.ee/eng/authors/p/pyramex/electro-1/) using SidWiz 2 (https://appdb.winehq.org/objectManager.php?sClass=application&iId=18581).

So loaded up E-Tracker and the module (in the zxart comments).
Recorded wav of all channels, followed by wav of individual channels.

Only to notice that the timing of the wav files seems very dodgy - when there is no output, the wav seems to not record.

I used [ Record / Audio as WAV / Record Audio ] - to be honest I have no idea what the difference is between 'Record Audio' and 'Record Segment'

[electo-1.zip](https://github.com/simonowen/simcoupe/files/2631205/electo-1.zip)

As a bonus - maybe a Record SidWiz2 (or so) could be added which records seven wav files simultaneously? A master.wav containing the result of all channels plus one wav per individual channel.

**Comment by simonowen** [comment]
Both audio recording options wait for the first frame of non-silence before starting.  "Record Audio" then continues until you stop it using the "Stop Recording" option on the same menu.  "Record Segment" will continue until there have been 2 seconds of silence, before automatically stopping (and trimming the trailing silence).  If audio continues before that 2 seconds are up, the buffered silence is added to the recording with the next non-silent data.

It worked when I originally tested it, but maybe the audio source I had didn't have any silence breaks that I would notice in the playback timing.  It sounds like you probably want "Record Audio" for manual control.  If it's still giving choppy audio then there's a bug to fix -- shout if you think there still is!

Recording separate channels would mean extending the SAASound library to expose the internal SAA channels for external mixing.  I expect to move away from the internal SAA code to the external [SAASound library](https://github.com/stripwax/saasound/), now that Dave Hooper has picked it up again. It may well be something Dave could add for me to optionally use.

**Comment by stefandrissen** [comment]
Thanks for the explanation of the difference between the two record options.

With record audio the silences are being gobbled up. You can test it with the following basic program:

    10 sound 20,63
    20 sound 0,255
    30 sound 8,255
    40 sound 16,4
    50 for i = 1 to 20
    60 sound 28,1
    70 pause 10
    80 sound 28,0
    90 pause 10
    100 next i

When run, an evenly timed beep is output.
When recorded, the silences are much too short resulting in a rushed beep.

**Comment by simonowen** [comment]
Fixed in 7bfad4147427484fc05212ff1f7f70cc00128a66. Thanks for the report and handy test program!
